### PR TITLE
Features and fixes from cburch824/KaosesTweaks

### PR DESCRIPTION
**Pull request by cburch824**
New Features:
- Toggle to prevent workshop ownership changes on certain events (war, bankruptcy)
- Add ability to change the rate at which new companions spawn (Vanilla: 6 weeks, new: every X weeks from 0 to 20)
- Allow users to change the minimum learning rate (Vanilla: 0, new: 0.0 to 16.0)

Changes:
- Replace the static smithing value with a multiplier. In short, an older version of Bannerlord had a static smithing stamina amount per character. It has since been updated to increase with smithing level. This allows us to use the new way while still letting players affect the value with a multiplier
- Increase possible workshop ownership limits to higher values
- Increase possible companion values to higher limits

### CODE REVIEW

**Comment by cburch824** [comment]
Hi @thetornadotitan , new features, fixes, and changes in this one. Tried to cover everything in the notes but it's possible I missed something. Let me know if you have any questions. Thanks!

**Comment by cburch824** [comment]
Actually I came across something here that may cause issues.

In KaosesSmithingPatches.cs, I fixed line 181 for the 1.7.1 Beta, but if I flip back to 1.7.0 I can't build our solution anymore. Any ideas on how to handle a solution that works for both versions?

**Comment by thetornadotitan** [comment]
I'd say we keep 1.7.0 as is and implement all future fixes in 1.7.1. Those on 1.7.0 will have to use as is and the latest version will stay with the beta version of the game. Super breaking bugs excluded.

**Review by thetornadotitan — APPROVED** [review]
Looks Good

**Pull request merged**
